<?php /* Smarty version 3.1.27, created on 2016-08-30 16:28:22
         compiled from "/data/wwwroot/www.minzhuzhihun.com/themes/mzzh/article.tpl" */ ?>
<?php
/*%%SmartyHeaderCode:143508555657c543a6161414_02469845%%*/
if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '88a2422d2dcf0f549d2bcad9797323c319450790' => 
    array (
      0 => '/data/wwwroot/www.minzhuzhihun.com/themes/mzzh/article.tpl',
      1 => 1471412166,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '143508555657c543a6161414_02469845',
  'variables' => 
  array (
    'title' => 0,
    'keywords' => 0,
    'description' => 0,
    'crumbs' => 0,
    'cb' => 0,
    'view_count' => 0,
    'tag' => 0,
    'content' => 0,
    'channel' => 0,
    'name' => 0,
    'url' => 0,
    'prev_page' => 0,
    'next_page' => 0,
  ),
  'has_nocache_code' => false,
  'version' => '3.1.27',
  'unifunc' => 'content_57c543a622cb80_09395744',
),false);
/*/%%SmartyHeaderCode%%*/
if ($_valid && !is_callable('content_57c543a622cb80_09395744')) {
function content_57c543a622cb80_09395744 ($_smarty_tpl) {
if (!is_callable('smarty_modifier_date_format')) require_once '/data/wwwroot/www.minzhuzhihun.com/includes/vendors/smarty/plugins/modifier.date_format.php';

$_smarty_tpl->properties['nocache_hash'] = '143508555657c543a6161414_02469845';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="/ssmay/style.css" rel="stylesheet" type="text/css" />
	<!--[if IE 6]>
	<link href="/ssmay/ie6.css" rel="stylesheet" type="text/css" />
	<?php echo '<script'; ?>
 src="http://letskillie6.googlecode.com/svn/trunk/letskillie6.zh_CN.pack.js"><?php echo '</script'; ?>
>
	<?php echo '<script'; ?>
 src="/ssmay/js/PNG.js"><?php echo '</script'; ?>
>
	<?php echo '<script'; ?>
>DD_belatedPNG.fix('.png_bg');<?php echo '</script'; ?>
>
	<![endif]-->
	<title><?php echo $_smarty_tpl->tpl_vars['title']->value;?>
 &laquo;  民族之魂钱币收藏网 </title>
	<meta name="keywords" content="<?php echo $_smarty_tpl->tpl_vars['keywords']->value;?>
" />
	<meta name="description" content="<?php echo $_smarty_tpl->tpl_vars['description']->value;?>
" />
	<meta name="author" content="钱币收藏"/>


<!-- START of style generated by wp-thumbnails 3.2.1 ，powered by niaolei.org.cn -->
<link rel="stylesheet" href="/ssmay/plugins/wp-thumbnails/style.css" type="text/css" media="screen" />
<!-- END of style generated by wp-thumbnails 3.2.1 ，powered by niaolei.org.cn -->
	<meta name="google-site-verification" content="Y6bxDsaSqdHB9bJ0SBL_m5QULJPrwtR77cdY9TJ2X-E" />
</head>
<body class="single single-post single-format-standard">
<div id="zhu_beijin">
<?php echo $_smarty_tpl->getSubTemplate ('./header.tpl', $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array(), 0);
?>

<div id="wrapper" class="clearfix">
	<div id="breadcrumbs" class="con_box clearfix">
		<div class="bcrumbs"><strong><a href="http://www.minzuzhihun.com" title="返回首页">home</a></strong>
		<?php
$_from = $_smarty_tpl->tpl_vars['crumbs']->value;
if (!is_array($_from) && !is_object($_from)) {
settype($_from, 'array');
}
$_smarty_tpl->tpl_vars['cb'] = new Smarty_Variable;
$_smarty_tpl->tpl_vars['cb']->_loop = false;
foreach ($_from as $_smarty_tpl->tpl_vars['cb']->value) {
$_smarty_tpl->tpl_vars['cb']->_loop = true;
$foreach_cb_Sav = $_smarty_tpl->tpl_vars['cb'];
?>
		<li><a href="<?php echo safe_url($_smarty_tpl->tpl_vars['cb']->value,false);?>
" rel="category tag"><?php echo $_smarty_tpl->tpl_vars['cb']->value['name'];?>
</a></li>
		<?php
$_smarty_tpl->tpl_vars['cb'] = $foreach_cb_Sav;
}
?>
		<li><?php echo $_smarty_tpl->tpl_vars['title']->value;?>
</li>
		</div>
	</div>
 	<div id="art_container clearfix">
 		<div id="art_main1" class="art_white_bg fl"> 
			            <div class="art_title clearfix">
           		<span class="face_img"><img alt='' src='http://0.gravatar.com/avatar/8a1cd6fd0b93f96f939390d202e2add7?s=50&amp;d=identicon&amp;r=G' class='avatar avatar-50 photo' height='50' width='50' /></span>
				<h1><?php echo $_smarty_tpl->tpl_vars['title']->value;?>
</h1>
				<p class="info">
				<small>栏目:</small><a href="<?php echo safe_url($_smarty_tpl->tpl_vars['crumbs']->value[0],false);?>
" rel="category tag"><?php echo $_smarty_tpl->tpl_vars['crumbs']->value[0]['name'];?>
</a> 
				<small>作者:</small>钱币收藏 
				<small>点击:</small> <?php echo number_format($_smarty_tpl->tpl_vars['view_count']->value);?>
 次</p><!-- /info -->  
			</div>
			<div class="article_content">
				<div class="article-tag">
				<?php if ($_smarty_tpl->tpl_vars['tag']->value) {?>
				<p><strong>本文标签</strong>： <a href="<?php echo tags_get_tag_url($_smarty_tpl->tpl_vars['tag']->value);?>
" rel="tag"><?php echo $_smarty_tpl->tpl_vars['tag']->value;?>
</a></p>
				<?php }?>
				</div>
				<?php echo $_smarty_tpl->tpl_vars['content']->value;?>

				<div class="adr">
	<div class="ad_r"><?php echo '<script'; ?>
 type="text/javascript">
    /*260*250右侧*/
    var cpro_id = "u1513840";
<?php echo '</script'; ?>
>
<?php echo '<script'; ?>
 src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"><?php echo '</script'; ?>
>	<div class="clear"></div>
	</div>
</div><!--内容广告2-->
<?php echo '<script'; ?>
 type="text/javascript">
/*民族之魂内容*/
var cpro_id = "u1585587";
<?php echo '</script'; ?>
>
<?php echo '<script'; ?>
 src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"><?php echo '</script'; ?>
>
				<div class="clear"></div>


<!--相关文章开始-->
<div class="similarity">
<br/><h5>相关文章：</h5>
<?php  $_smarty_tpl->tpl_vars['name'] = new Smarty_Variable;$_smarty_tpl->tpl_vars['name']->_loop = false;
 $_name_data = get_data_from_cts_provider('pages', array('model'=>'news','channel'=>$_smarty_tpl->tpl_vars['channel']->value,'flags'=>'j','random'=>'on','sortby'=>'id','order'=>'d','limit'=>'0,6','pp'=>'off','nocache'=>false),$_smarty_tpl->tpl_vars);
 $_smarty_tpl->tpl_vars['name_total'] = new Smarty_Variable;
 $_smarty_tpl->tpl_vars['name_total']->value = $_name_data['size'];
 $_from = $_name_data;
if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['name']->key => $_smarty_tpl->tpl_vars['name']->value){
$_smarty_tpl->tpl_vars['name']->_loop = true;
?>
<li><span><a href="<?php echo safe_url($_smarty_tpl->tpl_vars['name']->value,false);?>
" rel="bookmark" title="<?php echo $_smarty_tpl->tpl_vars['name']->value['title'];?>
"><?php echo $_smarty_tpl->tpl_vars['name']->value['title'];?>
</a></span> <span id="shijian"><?php echo smarty_modifier_date_format($_smarty_tpl->tpl_vars['name']->value['update_time'],'Y-m-d');?>
</span></li>
<?php } ?>
</div><!--相关文章结束-->
				
				<div class="adt">
	<div class="ad_t"><?php echo '<script'; ?>
 type="text/javascript">
/*640*60，创建于2014-4-6*/
var cpro_id = "u1513811";
<?php echo '</script'; ?>
>
<?php echo '<script'; ?>
 src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"><?php echo '</script'; ?>
>	<div class="clear"></div>
	</div>
</div>				
				<div class="clear"></div>
            			
				<div class="postcopyright">
					<p><strong> 声明: </strong> 本文由(<a href="http://www.minzuzhihun.com"> 钱币收藏 </a>)原创编译，转载请保留链接: <a href="<?php echo $_smarty_tpl->tpl_vars['url']->value;?>
" title="<?php echo $_smarty_tpl->tpl_vars['title']->value;?>
"><?php echo $_smarty_tpl->tpl_vars['title']->value;?>
</a></p>
				</div>
							</div><!--正文--> 
			<div class="con_pretext clearfix">
					<ul>
						<?php if ($_smarty_tpl->tpl_vars['prev_page']->value) {?>
						<li class="first">上一篇：<a href="<?php echo safe_url($_smarty_tpl->tpl_vars['prev_page']->value,false);?>
" rel="prev"><?php echo $_smarty_tpl->tpl_vars['prev_page']->value['title'];?>
</a> </li>
						<?php }?>
						<?php if ($_smarty_tpl->tpl_vars['next_page']->value) {?>
						<li class="last">下一篇：<a href="<?php echo safe_url($_smarty_tpl->tpl_vars['next_page']->value,false);?>
" rel="next"><?php echo $_smarty_tpl->tpl_vars['next_page']->value['title'];?>
</a></li>
						<?php }?>
					</ul>	       
			</div>   		
				<div class="clear"></div>
		</div><!--内容-->

			
	
		<div class="clear"></div>
		

         <!--侧边栏-->
<div id="sider" class="fr">
<?php echo $_smarty_tpl->getSubTemplate ('./sidebar.tpl', $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array(), 0);
?>

</div>
</div> 
</div><!-- //wrapper -->
<!-- //底部模板 -->
<?php echo $_smarty_tpl->getSubTemplate ('./foot.tpl', $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array(), 0);
?>

</div>
<!-- 头部JS -->
<?php echo '<script'; ?>
 type="text/javascript" src="/ssmay/js/jquery.min.js"><?php echo '</script'; ?>
>	
<?php echo '<script'; ?>
 type="text/javascript">HcmsLazyload("/ssmay/images/space.gif");<?php echo '</script'; ?>
> 
<?php echo '<script'; ?>
 type="text/javascript">window.jQuery || document.write('<?php echo '<script'; ?>
 type="text/javascript" src="/ssmay/js/jquery.js">\x3C/script>')<?php echo '</script'; ?>
>
<?php echo '<script'; ?>
 type="text/javascript" src="/ssmay/js/jquery_ssmay.js"><?php echo '</script'; ?>
>
<!-- 头部JS -->


<?php echo '<script'; ?>
>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"16"},"slide":{"type":"slide","bdImg":"4","bdPos":"right","bdTop":"100"}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];<?php echo '</script'; ?>
>

<?php echo '<script'; ?>
 type="text/javascript">
    /*图加*/
var cpro_id = "u1688336";
<?php echo '</script'; ?>
>
<?php echo '<script'; ?>
 src="http://cpro.baidustatic.com/cpro/ui/i.js" type="text/javascript"><?php echo '</script'; ?>
>
</body>
</html><?php }
}
?>