<?php
//generated by kissgo,don't edit this file manually!
defined('KISSGO') or exit('No direct script access allowed');
$settings = KissGoSetting::getSetting();

$settings['DEBUG'] = 4;

$settings['CLEAN_URL'] = true;

$settings['I18N_ENABLED'] = true;

$settings['GZIP_ENABLED'] = false;

$settings['TIMEZONE'] = 'Etc/GMT-8';

$settings['SECURITY_KEY'] = 'JhlEiDR16gefmsRX';

$settings['database'] = array (
  'default' => 
  array (
    'driver' => 'MySQL',
    'host' => '127.0.0.1',
    'port' => '3306',
    'dbname' => 'wentongnew',
    'prefix' => '',
    'user' => 'root',
    'password' => 'root',
    'encoding' => 'UTF8',
  ),
);

// end of F:\wamp\www\6\appdata\settings.php
?>